AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a VPC with 1 public subnet and 1 private subnet

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: tech-excellence-VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: tech-execellence-IGW

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: PublicRouteTable
  
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: PrivateRouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  NATGatewayEIP:
    Type: AWS::EC2::EIP
    DependsOn: AttachGateway
    Properties:
      Domain: vpc

  NATGateway:
    Type: AWS::EC2::NatGateway
    DependsOn: AttachGateway
    Properties:
      AllocationId: !GetAtt NATGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: MyNATGateway
  
  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: PublicSubnet

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: PrivateSubnet

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PublicRouteTable
   
  PublicSecurityGroup:
   Type: AWS::EC2::SecurityGroup
   Properties:
     GroupDescription: Public security group
     VpcId: !Ref MyVPC
     SecurityGroupIngress: 
       - IpProtocol: tcp # allows all tcp inbound traffic 
         CidrIp: 0.0.0.0/0
     SecurityGroupEgress:
       - IpProtocol: -1 # allows all outbound traffic
         CidrIp: 0.0.0.0/0
     Tags:
       - Key: Name
         Value: PublicSecurityGroup

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Private security group
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: -1 # Allows all inbound traffic from within the VPC
          CidrIp: 10.0.0.0/16
      SecurityGroupEgress:
        - IpProtocol: -1 # Allows all outbound traffic from within the VPC
          CidrIp: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: PrivateSecurityGroup

Outputs:
  VPCId:
    Description: VPC Id
    Value: !Ref MyVPC

  PublicSubnetId:
    Description: Public Subnet Id
    Value: !Ref PublicSubnet

  PrivateSubnetId:
    Description: Private Subnet Id
    Value: !Ref PrivateSubnet

  PublicSecurityGroupId:
    Description: Public Security Group Id
    Value: !Ref PublicSecurityGroup

  PrivateSecurityGroupId:
    Description: Private Security Group Id
    Value: !Ref PrivateSecurityGroup

  PublicRouteTableId:
    Description: Public Route Table Id
    Value: !Ref PublicRouteTable

  PrivateRouteTableId:
    Description: Private Route Table Id
    Value: !Ref PrivateRouteTable
